language: go

sudo: false

go:
- 1.12.5

env:
- GO111MODULE=on

before_install:
  - go get github.com/mattn/goveralls

install:
- go get -t ./...

script:
  - $GOPATH/bin/goveralls -service=travis-ci
