language: go

sudo: false

go:
- 1.14
- 1.15

env:
  - GO111MODULE=on


install:
  - go get -t ./...
  - go get -u github.com/caddyserver/xcaddy/cmd/xcaddy

before_script:
  - xcaddy build

script:
  - go test -v -coverprofile="cover-profile.out" -short -race ./...
